[[constraint]]
  name = "git.apache.org/thrift.git"
  version = "0.9.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[prune]
  go-tests = true
  unused-packages = true
